"""Add packing slips and update invoice

Revision ID: 0e794dbdb895
Revises: de6e13cd7fee
Create Date: 2026-04-02 19:25:54.505238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e794dbdb895'
down_revision = 'de6e13cd7fee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packing_slips',
    sa.Column('pslip_id', sa.String(), nullable=False),
    sa.Column('coid', sa.String(), nullable=False),
    sa.Column('packed_by', sa.String(), nullable=False),
    sa.Column('packed_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['coid'], ['customer_orders.coid'], ),
    sa.ForeignKeyConstraint(['packed_by'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('pslip_id')
    )
    op.create_table('packing_slip_details',
    sa.Column('psd_id', sa.String(), nullable=False),
    sa.Column('pslip_id', sa.String(), nullable=False),
    sa.Column('skuid', sa.String(), nullable=False),
    sa.Column('packed_qty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pslip_id'], ['packing_slips.pslip_id'], ),
    sa.ForeignKeyConstraint(['skuid'], ['skus.skuid'], ),
    sa.PrimaryKeyConstraint('psd_id')
    )
    with op.batch_alter_table('customer_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pslip_id', sa.String(), nullable=False))
        batch_op.drop_constraint(batch_op.f('customer_invoices_coid_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'packing_slips', ['pslip_id'], ['pslip_id'])
        batch_op.drop_column('coid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coid', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('customer_invoices_coid_fkey'), 'customer_orders', ['coid'], ['coid'])
        batch_op.drop_column('pslip_id')

    op.drop_table('packing_slip_details')
    op.drop_table('packing_slips')
    # ### end Alembic commands ###
