"""modify 1 column in customer table

Revision ID: 1184b62e2f5f
Revises: 5dccf55b586d
Create Date: 2026-04-01 22:27:57.059074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1184b62e2f5f'
down_revision = '5dccf55b586d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acp', sa.Integer(), nullable=True))
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('acp')

    # ### end Alembic commands ###
