"""add ranking tables

Revision ID: 1449f90cb979
Revises: 19e99e4fda70
Create Date: 2026-04-14 12:39:09.695700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1449f90cb979'
down_revision = '19e99e4fda70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('high_priority_rankings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coid', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coid', 'status', name='uq_high_card_status')
    )
    op.create_table('low_priority_rankings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coid', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coid', 'status', name='uq_low_card_status')
    )
    op.create_table('medium_priority_rankings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coid', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coid', 'status', name='uq_medium_card_status')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medium_priority_rankings')
    op.drop_table('low_priority_rankings')
    op.drop_table('high_priority_rankings')
    # ### end Alembic commands ###
