"""add delivery receipts

Revision ID: 19e99e4fda70
Revises: 0e794dbdb895
Create Date: 2026-04-03 19:59:01.745296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19e99e4fda70'
down_revision = '0e794dbdb895'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_receipts',
    sa.Column('receipt_id', sa.String(), nullable=False),
    sa.Column('cinv_id', sa.String(), nullable=False),
    sa.Column('received_by', sa.String(), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cinv_id'], ['customer_invoices.cinv_id'], ),
    sa.ForeignKeyConstraint(['received_by'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('receipt_id')
    )
    op.create_table('delivery_receipt_details',
    sa.Column('dr_detail_id', sa.String(), nullable=False),
    sa.Column('receipt_id', sa.String(), nullable=False),
    sa.Column('skuid', sa.String(), nullable=False),
    sa.Column('received_qty', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['receipt_id'], ['delivery_receipts.receipt_id'], ),
    sa.ForeignKeyConstraint(['skuid'], ['skus.skuid'], ),
    sa.PrimaryKeyConstraint('dr_detail_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery_receipt_details')
    op.drop_table('delivery_receipts')
    # ### end Alembic commands ###
