"""Add TotalAmount to orders

Revision ID: 3a36f85bd1ad
Revises: 8f703a31e8ce
Create Date: 2026-04-02 12:48:36.613573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a36f85bd1ad'
down_revision = '8f703a31e8ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('vendor_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_orders', schema=None) as batch_op:
        batch_op.drop_column('total_amount')

    with op.batch_alter_table('customer_orders', schema=None) as batch_op:
        batch_op.drop_column('total_amount')

    # ### end Alembic commands ###
