"""Add amount to order details

Revision ID: 529c1fa6f09a
Revises: 3a36f85bd1ad
Create Date: 2026-04-02 13:07:05.017707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '529c1fa6f09a'
down_revision = '3a36f85bd1ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_order_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('vendor_order_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_order_details', schema=None) as batch_op:
        batch_op.drop_column('amount')

    with op.batch_alter_table('customer_order_details', schema=None) as batch_op:
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
