"""schema update - restructure SKU pricing, move vendor_prefix, remove tracking_num and unit_measurement

Revision ID: 5dccf55b586d
Revises: 8d245daa6ac6
Create Date: 2026-03-31 19:59:25.182432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dccf55b586d'
down_revision = '8d245daa6ac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispatches', schema=None) as batch_op:
        batch_op.drop_column('tracking_num')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('unit_measurement')

    with op.batch_alter_table('skus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_measurement_buy', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lot_size_buy', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_buy_rate', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('unit_measurement_sell', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lot_size_sell', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_sell_rate', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.drop_column('current_sell')
        batch_op.drop_column('current_buy')

    with op.batch_alter_table('vendor_products', schema=None) as batch_op:
        batch_op.drop_column('vendor_prefix')

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_prefix', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_column('vendor_prefix')

    with op.batch_alter_table('vendor_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_prefix', sa.VARCHAR(), autoincrement=False, nullable=True))

    with op.batch_alter_table('skus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_buy', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('current_sell', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.drop_column('current_sell_rate')
        batch_op.drop_column('lot_size_sell')
        batch_op.drop_column('unit_measurement_sell')
        batch_op.drop_column('current_buy_rate')
        batch_op.drop_column('lot_size_buy')
        batch_op.drop_column('unit_measurement_buy')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_measurement', sa.VARCHAR(), autoincrement=False, nullable=True))

    with op.batch_alter_table('dispatches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tracking_num', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
