"""add lead_time to vendors

Revision ID: 786a25bf4c12
Revises: 19e99e4fda70
Create Date: 2026-04-18 19:13:30.697777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '786a25bf4c12'
down_revision = '19e99e4fda70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_time', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_column('lead_time')

    # ### end Alembic commands ###
