"""Add CustomerOrderDetail model

Revision ID: 8f703a31e8ce
Revises: 1184b62e2f5f
Create Date: 2026-04-02 11:36:29.096289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f703a31e8ce'
down_revision = '1184b62e2f5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_order_details',
    sa.Column('codid', sa.String(), nullable=False),
    sa.Column('coid', sa.String(), nullable=False),
    sa.Column('skuid', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coid'], ['customer_orders.coid'], ),
    sa.ForeignKeyConstraint(['skuid'], ['skus.skuid'], ),
    sa.PrimaryKeyConstraint('codid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_order_details')
    # ### end Alembic commands ###
