"""add coid to payment

Revision ID: a50309bf61c3
Revises: 1449f90cb979
Create Date: 2026-04-14 13:56:31.992711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a50309bf61c3'
down_revision = '1449f90cb979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coid', sa.String(), nullable=True))
        batch_op.alter_column('cinv_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_foreign_key(None, 'customer_orders', ['coid'], ['coid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('cinv_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('coid')

    # ### end Alembic commands ###
