"""Add amount to invoice details

Revision ID: c770f1b4fa8d
Revises: 529c1fa6f09a
Create Date: 2026-04-02 13:09:28.286155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c770f1b4fa8d'
down_revision = '529c1fa6f09a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_inv_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('vendor_invoice_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_invoice_details', schema=None) as batch_op:
        batch_op.drop_column('amount')

    with op.batch_alter_table('customer_inv_details', schema=None) as batch_op:
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
