"""Add TotalAmount to invoices

Revision ID: de6e13cd7fee
Revises: c770f1b4fa8d
Create Date: 2026-04-02 13:16:14.057589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de6e13cd7fee'
down_revision = 'c770f1b4fa8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('vendor_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_invoices', schema=None) as batch_op:
        batch_op.drop_column('total_amount')

    with op.batch_alter_table('customer_invoices', schema=None) as batch_op:
        batch_op.drop_column('total_amount')

    # ### end Alembic commands ###
